src/drug_store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/schema", SpectacularAPIView.as_view(), name="schema"),
    # Optional UI:
    path(
        "api/swagger-ui/",
        SpectacularSwaggerView.as_view(),
        name="swagger-ui",
    ),
    path(
        "api/redoc/",
        SpectacularRedocView.as_view(),
        name="redoc",
    ),
    path("api/auth/", include("auth_app.urls")),
    path("api/users/", include("users_app.urls")),
    path("api/drugs/", include("drugs_app.urls")),
    path("api/orders/", include("orders_app.urls")),
    path("api/notifications/", include("notifications_app.urls")),
    path("prometheus/", include("django_prometheus.urls")),
    path("", include("authentication.urls")),
    path("", include("users.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/frontend/users/urls.py
from django.urls import path

from . import views

app_name = "user"

urlpatterns = [
    path("profile", views.profile, name="profile"),
    path("orders/current", views.current_orders, name="current-orders"),
    path("orders/archived", views.archived_orders, name="arch-orders"),
    path("orders/create", views.create_order, name="create-order"),
    path("users", views.add_users, name="users-page"),
    path("drugs", views.add_drugs, name="drugs-page"),
]

src/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      type="text/css"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="https://pyscript.net/latest/pyscript.css" />
    <script defer src="https://pyscript.net/latest/pyscript.js"></script>
    
    <title>{{title}}</title>
  </head>
  <body>
    <py-config src="{% static 'ps/pyscript.toml' %}"></py-config>
    {% block content %} {% endblock %} {% include 'base/footer.html' %}
    <script
      src="tps://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

src/templates/base/footer.html
{% load static %}
<style type="text/css">
  .footer {
    background: url("{% static '/assets/images/national-cancer.png' %}") center
      no-repeat;
    background-size: cover;
    color: white;
  }
  .background-layer {
    background-color: rgba(0, 147, 221, 0.7);
    width: 100%;
    height: 100%;
  }
</style>
<footer class="footer">
  <div class="background-layer">
    <div class="container p-5">
      <div class="row">
        <div class="col-md-6">
          <div>
            <a class="navbar-brand" href="#"
              ><img
                src='{% static "/assets/icons/logo-removebg-p.svg" %}'
                alt="Logo"
            /></a>
            <span class="pl-5" style="font-size: 25px"
              >Gaza Central Company</span
            >
          </div>
          <div class="pt-2">
            Lorem Ipsum is simply dummy text of the printing and typesetting
            industry. Lorem Ipsum has been the industry's standard dummy text
            ever since the 1500s, when an unknown printer took a galley of type
            and scrambled it to make a type specimen book. It has survived not
            only five centuries, but also the leap into electronic typesetting,
            remaining essentially unchanged. It was popularised in th.
          </div>
        </div>
        <div class="col-md-6">
          <p>&copy; 2023 My Website. All rights reserved.</p>
        </div>
      </div>
      <hr class="mt-3" style="width: 100%; color: white" />
    </div>
  </div>
</footer>

src/templates/base/navbar.html
{% load static %}
<link
  rel="stylesheet"
  type="text/css"
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
/>
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
/>

<py-script>
  import js, json 
  auth_data = js.localStorage.getItem("auth_data") 
  if auth_data is None:
    js.window.location.replace(f"http://localhost:8000/auth/login") 
  auth_data = json.loads(auth_data) 
  js.document.getElementById("profilepicture").src = auth_data["profile_pic"] 
  if auth_data["is_staff"]:
    js.document.getElementsByName("forpharmacy")[0].style.display = "none" 
  else:
    js.document.getElementsByName("foradmin")[0].style.display = "none"
    js.document.getElementsByName("foradmin")[1].style.display = "none"
</py-script>

<py-script src="{% static 'ps/auth.py' %}"> </py-script>

<script>

  function count_notifications(){
    notifs_count = document.getElementById("notifications").children.length
    document.getElementById("notifications_count").innerHTML = notifs_count - 1
  }

  // Create WebSocket connection.
  auth_data = JSON.parse(localStorage.getItem("auth_data"));
  const socket = new WebSocket(
    `ws://localhost:8000/api/notifs/me?token=${auth_data["token"]}`
  );

  // Connection opened
  socket.addEventListener("open", function (event) {
    socket.send(JSON.stringify({"message": "Hello Server!"}));
    count_notifications()
  });

  // Listen for messages
  socket.addEventListener("message", function (event) {
    console.log("Message from server ", JSON.parse(event.data));
    message = JSON.parse(event.data).data.message
    notifs = document.getElementById("notifications")
    notifs.innerHTML += `
      <li class="dropdown-item">
        ${message}
      </li>
    `
    count_notifications()
  });
  
</script>

<nav class="navbar navbar-expand-lg fixed-top bg-primary navbar-light">
  <div class="container">
    <a class="navbar-brand" href="#">
      <img
        id="logo"
        src="{% static 'assets/icons/logo-removebg-p.svg' %}"
        alt="MDB Logo"
        draggable="false"
        height="30"
      />
    </a>
    <!-- Menu button -->
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto my-2 my-lg-0">
        <li class="nav-item">
          <a class="nav-link" style="color: white" href="#home">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:current-orders' %}"
            >Current Orders</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:arch-orders' %}"
            >Archived Orders</a
          >
        </li>
        <li class="nav-item" name="foradmin">
          <a class="nav-link" href="{% url 'user:users-page' %}">Users</a>
        </li>
        <li class="nav-item" name="foradmin">
          <a class="nav-link" href="{% url 'user:drugs-page' %}">Drugs</a>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto align-items-center">
        <li class="nav-item" name="forpharmacy">
          <a class="nav-link mx-2" href="{% url 'user:create-order' %}"
            ><i class="fas fa-plus-circle pe-2"></i>Order</a
          >
        </li>
        <li class="nav-item dropdown text-center mx-2 mx-lg-1">
          <a
            class="nav-link"
            href="#"
            aria-expanded="false"
            id="navbarDropdownMenuLink"
            role="button"
            data-bs-toggle="dropdown"
          >
            <div>
              <i class="fas fa-bell"></i>
              <span class="badge rounded-pill badge-notification bg-primary"
                    id="notifications_count"
                    style="color: red;"
                >0</span
              >
            </div>
          </a>

          <ul
            class="dropdown-menu dropdown-menu-end"
            aria-labelledby="navbarDropdownMenuLink"
            id="notifications"
          >
            <li><h6 class="dropdown-header">Notifications</h6></li>
          </ul>
        </li>
        <li class="nav-item ms-3 dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdownMenuLink"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            <img
              src="https://bootdey.com/img/Content/avatar/avatar7.png"
              alt="Profile"
              id="profilepicture"
              style="height: 30px; width: 30px;"
              class="avatar-sm rounded-circle me-2"
            />
          </a>
          <ul
            class="dropdown-menu dropdown-menu-end"
            aria-labelledby="navbarDropdownMenuLink"
          >
            <li>
              <a class="dropdown-item" href="{% url 'user:profile' %}"
                >Profile</a
              >
            </li>
            <li><hr class="dropdown-divider" /></li>
            <li><a class="dropdown-item" py-click="logout()">Logout</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
<!-- Navbar -->
<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
  crossorigin="anonymous"
></script>